/// Embedded default configuration and presets, compiled into the binary.
///
/// These are used as fallbacks when external config files are not found,
/// enabling the executable to run standalone without any external files.

/// The default configuration TOML, embedded at compile time.
pub const DEFAULT_CONFIG: &str = include_str!("../../../config/default.toml");

// Preset array generated by build.rs: &[("preset_name", "toml_content")]
include!(concat!(env!("OUT_DIR"), "/presets_embedded.rs"));

/// Look up an embedded preset by name.
#[must_use]
pub fn find_preset(name: &str) -> Option<&'static str> {
    EMBEDDED_PRESETS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, content)| *content)
}

/// Return all embedded preset names, sorted.
#[must_use]
pub fn preset_names() -> Vec<&'static str> {
    EMBEDDED_PRESETS.iter().map(|(n, _)| *n).collect()
}
