#![allow(clippy::expect_used)]

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let presets_dir = Path::new("../../config/presets");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("presets_embedded.rs");

    let mut entries: Vec<(String, String)> = Vec::new();

    if presets_dir.is_dir() {
        let mut paths: Vec<_> = fs::read_dir(presets_dir)
            .expect("cannot read config/presets")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
            .collect();
        paths.sort();

        for path in &paths {
            let name = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("invalid preset filename");
            let abs = fs::canonicalize(path).expect("cannot canonicalize preset path");
            entries.push((name.to_string(), abs.to_string_lossy().into_owned()));
            // Tell cargo to rerun if any preset changes
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let mut f = fs::File::create(&dest).expect("cannot create presets_embedded.rs");

    writeln!(f, "/// Embedded preset configs, generated by build.rs.").ok();
    writeln!(f, "pub const EMBEDDED_PRESETS: &[(&str, &str)] = &[").ok();
    for (name, abs_path) in &entries {
        // Use include_str! with the absolute path so cargo tracks the file
        let escaped = abs_path.replace('\\', "\\\\");
        writeln!(f, "    (\"{name}\", include_str!(\"{escaped}\")),").ok();
    }
    writeln!(f, "];").ok();

    // Also rerun if the presets directory itself changes (new/deleted files)
    println!("cargo:rerun-if-changed=../../config/presets");
    // Track the default config too
    println!("cargo:rerun-if-changed=../../config/default.toml");
}
